In [36]:
import numpy as np

In [37]:
#задание 1. Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).
def make_array(N):
    y=np.arange(N-1,-1,-1)
    return y
    

In [39]:
x1=make_array(10)
x1

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [6]:
#задание 2. Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.
def task_2(array):
    m=np.diag(array)
    s=array.sum()
    return m,s


In [13]:
matrix,sum_diag=task_2(make_array(10))
print('Матрица:\n',matrix)
print('\nСумма диагонали: ',sum_diag)

Матрица:
 [[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]

Сумма диагонали:  45


In [19]:
#задание 3.  Задание 3
#Решите систему уравнений:
#4x + 2y + z = 4
#x + 3y = 12
#5y + 4z = -3

A=np.array([[4,2,1],[1,3,0],[0,5,4]])
b=np.array([4,12,-3])
#считаем обратную матрицу от А
B=np.linalg.inv(A)
#умножим матрично B на b
sol=np.dot(B,b)
print ('x=', round(sol[0],2))
print ('y=', round(sol[1],2))
print ('z=', round(sol[2],2))

x= 0.47
y= 3.84
z= -5.56


In [21]:
#задание 4. Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и 
#всеми пользователями из массива user_stats

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [22]:
def cosine( a, b ):
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [24]:
users_stats[0]

array([2, 1, 0, 0, 0, 0], dtype=int32)

In [35]:
sim=[]
for user_vector in users_stats:
    sim.append(cosine(user_vector,next_user_stats))
max_sim=max(sim)
print("Самый похожий пользователь с ID -", sim.index(max_sim)+1) 
print("\nКосинусное сходство = ", max_sim)

Самый похожий пользователь с ID - 8

Косинусное сходство =  0.9486832980505138
